#spring:
#  h2:
#    console:
#      enabled: true

#logging:
#  level:
#    org:
#      springframework:
#        web: trace


spring:
  security:
    user:
      name: user
      password: pass
      roles: 'ADMIN'